spring:
  application:
    name: api-target
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false