server:
  port: 8000
  servlet:
    context-path: /api/target
spring:       
  application:
    name: api-target
  profiles:
    active:
    - "test"
	
	
	spring:
	  application:
	    name: api-webfit
	  
	  datasource:
	    url: jdbc:h2:mem:testdb
	    username: sa
	    password: 
	    driverClassName: org.h2.Driver

	  jpa:
	    show-sql: true
	    ddl-auto: update
	    database-platform: org.hibernate.dialect.H2Dialect

	  jackson:
	    default-property-inclusion: NON_NULL
	    serialization:
	      fail-on-empty-beans: false